# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build
on:
  push:
    branches:
      - dev
      - feat/arm64-docker-builds
    paths-ignore:
      - 'version.py'

jobs:
  publish_alpha_release:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@master
    secrets: inherit
    with:
      version_file: "version.py"
      setup_py: "setup.py"
      publish_prerelease: true
  build_and_publish_docker:
    needs: publish_alpha_release
    uses: neongeckocom/.github/.github/workflows/publish_docker.yml@master
    secrets: inherit
    with:
      platforms: linux/amd64,linux/arm64